### ISSUE TITLE
Transaction has been reverted by the EVM en exampleFirstEntity

### ISSUE THREAD

**Issue by jcarovestigia** [alastria/alastria-identity-example#107]
Buenas noches. Intento sin éxito montar un sistema de identidad Alastria. Entiendo que debo comenzar por crear una primera entidad emisora de identidades, y he supuesto que debo ejecutar los scripts del ejemplo "exampleFirstEntity". Me encuentro, sin embargo, con que la EVM me tira (revert) los intentos de ejecutar prepareAlastriaID, ejecutado por la dirección "owner" (dirección con la que he desplegado los contratos, con el script 2.deployUpdateContracts.js) con otra dirección "entity1" como parámetro. Deduzco que se debe a que la dirección owner no está lógicamente en el mapping identityKeys (identityKeys[owner]==address(0)). ¿Cómo se hace? ¿Debo hacer operaciones previas? Las direcciones de contratos y cuentas, así como los ficheros UTC y claves están modificados aparentemente correctamente en los ficheros de configuración correspondientes.

**Comment by jcarovestigia** [comment]
Acabo de caer en la cuenta: no se deben desplegar nuevos contratos, sino usar los existentes ¿no? De todas formas ¿cómo se haría, partiendo de cero? ¿Cómo se registraría la dirección owner en identityKeys?

**Comment by VictorNS69** [comment]
Entiendo que estás hablándome de la rama **master**, ¿no?

Hola, la verdad es que este fallo que estás teniendo es porque no está bien documentado. Para la siguiente versión de contratos, se hará automaticamente todo.

El problema es que la cuenta con la que has desplegado **no es issuer (su proxy)**. En los contratos de master, no se hace automáticamente.

Para hacer la cuenta de despliegue issuer, tienes que **lanzar un script** después de desplegar. El script lo puedes encontrar en esta PR https://github.com/alastria/alastria-identity/pull/125, pero **tienes que cambiar ciertos datos** (en tx1, tx2 y tx3). Este script se ejecuta con `truffle exec setAdminProxy.js --network <red en el truffle.config>`

**Comment by jcarovestigia** [comment]
Muchas gracias, pero no me funciona. Sigue dando el mismo error. Probablemente estoy configurando mal los tx_, aunque no me da fallo el script. ¿Crees que sería mejor que usara los contratos de la rama develop?

**Comment by VictorNS69** [comment]
De momento usa rama Master, ya que Develop está en desarrollo ahora mismo. Tendría ya que mirar más en detalle lo que has montado. No sé si mejor hablarlo por slack o similar.

Si no, podemos continuar por aquí con capturas de pantalla

**Comment by jcarovestigia** [comment]
Espera, ya veo el problema. El script alastria/alastria-identity#125 hace "IdentityIssuer" a la dirección del proxy de la cuenta admin, no a la dirección de admin (esto es necesario porque transactionFactory llama a prepareAlastriaID a través del proxy, con una llamada no delegada, y esta llamada exige que el solicitante (el proxy) sea IdentityIssuer). ¡Pero yo no tengo la dirección del proxy de admin!! ¿De dónde la saco?

**Comment by VictorNS69** [comment]
Exacto, lo vas pillando. Con `tx1` y `tx2` se crea el proxy. Una vez creado, tienes que mirar el contrato (usando remix-ide o por código) el mapping `identityKeys` que le pasas el address (del keystore) de la cuenta (admin en este caso) y te devuelve su proxy address.

De nuevo perdona que falte documentación sobre todo este tema :disappointed:

**Comment by jcarovestigia** [comment]
No sé cómo verlo con remix ¿Puedo añadir una funcion view al contrato https://github.com/alastria/alastria-identity/blob/master/contracts/identityManager/AlastriaIdentityManager.sol que me la dé? por ejemplo:
`function myIdentity() public view returns(address mine){
    mine=address(identityKeys[msg.sender]);
}`
¿O eso comprometería de alguna forma la privacidad de los datos o el modelo de Alastria ID?

**Comment by VictorNS69** [comment]
No hay necesidad de eso que pides. En el contrato, el mapping que necesitas consumir es público, es decir, cualquiera puede leerlo. 
https://github.com/alastria/alastria-identity/blob/da37badfc1a8d7f6ef52cb5261d25b8d55622cd4/contracts/identityManager/AlastriaIdentityManager.sol#L19

Si no conoces remix-ide, puedes leer documentación aquí. Es fácil de utilizar. https://remix-ide.readthedocs.io/en/latest/create_deploy.html

Si no, solo tienes que llamar (hacer una `call`) al mapping que te comento, al igual que llamas a otra función.

**Comment by jcarovestigia** [comment]
Funcionó al fin. Muchas gracias.

**Comment by VictorNS69** [comment]
Perfecto, cierro el issue.

**Comment by rosdec** [comment]
Hi @jcarovestigia it seems you've succeded in what we are currently trying to do, deploying Alastria Identity smart contracts on a private blockchain starting from scratch. Would you mind to share with me which the correct sequence of scripts to be called to happily deploy the smart contracts?

Thank you in advance

**Comment by jcarovestigia** [comment]
Gladly. But actually I didn't deploy it on a private blockchain, but in Alastria Telsius blockchain.
If that's your case, start downgrading your nodejs to 10.23.0. Clone https://github.com/alastria/alastria-identity.git and install with npm install, as recommended. Create an "admin" account in the blockchain. Modify "config.json": "nodeURLAlastria", "addressPwdAlastria" and "addressPosition" as appropriate (be sure you get the correct index of your admin account in eth.accounts). Deploy contracts with node 1.flattenContracts.js, then node 2.deployUpdateContracts.js. Now you should get the contracts addresses. Tell me.
