### ISSUE TITLE
Create AlastriaIdentityRecovery (AIR) example

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-example#115]
We need to add a new example for recovering the identity.

This issue is blocked  by https://github.com/alastria/alastria-identity-lib/issues/150

This new example should follow the flow described in https://github.com/alastria/alastria-identity/wiki/Alastria-ID-flows#3-alastria-id-recovery-us-3x

**Note that at the moment, the Smart Contracts don't implement the "recover Alastria Identity" functionality**, so this part in the example must be fake for now

**Comment by rober12** [comment]
This object will no longer be necessary. It is closed because it is obsolete
