### ISSUE TITLE
Remove the signature of the Alastria Token by the subject

### ISSUE THREAD

**Issue by rober12** [alastria/alastria-identity-example#126]
In the examples of identity creation an error has been found where the subject before building the AIC re-signs the AT to include it in the AIC. This is incorrect, the AT should not be signed by the subject.

This problem exist in the following examples:

- 1.createEntity2AlastriaID.js
- 2.createEntity3AlastriaID.js
- 3.createSubject1AlastriaID.js
- 4.createSubject2AlastriaID.js

![image](https://user-images.githubusercontent.com/17437316/134638505-67b47237-61f7-46d8-b767-f621a2a8d866.png)

**Comment by VictorNS69** [comment]
Duplicated #103
