### ISSUE TITLE
FIX-1. Examples Callback en Presentation Requests

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-example#44]
Tras cerrar el issue de la librería https://github.com/alastria/alastria-identity/issues/49

Será necesario añadir un parámetro en aquellos examples que utilicen la función createPresentationRequest

**Comment by VictorNS69** [comment]
@amoral-eurogestion , por lo que estoy viendo, no tenemos a día de hoy ninguna implementación de ejemplo de cómo se llama a este método (createPresentationRequest). Esto es debido a que como básicamente es generar un JSON (JWT) con la librería, y no hay nada on-chain, se nos ha debido pasar.

Yo diría de añadir un ejemplo de la llamada al método en el archivo [1.tokenFactory.js](https://github.com/alastria/alastria-identity-example/blob/develop/exampleTokens/1.tokenFactory.js).

Ahí, lo único que tienes que hacer es una llamada de ejemplo al método, pero obteniendo todos los datos necesarios (como el _iss_, _cbu_, etc) del archivo [configuration.json](https://github.com/alastria/alastria-identity-example/blob/develop/configuration.json).

Echa un vistazo al resto de ejemplos y si te surge cualquier duda nos preguntas.
