### ISSUE TITLE
FIX-2. Example DIDs en vez de AlastriaProxy address

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-example#45]
Tras cerrar el issue de la librería https://github.com/alastria/alastria-identity/issues/50

Es necesario modificar los examples para enviar como parámetro el DID en vez del AlastriaProxy en todas las funciones

Se recomienda actualizar la librería en la demo-entity

Se recomienda actualizar el uso de librerías en el wallet

**Comment by jotafernandez** [comment]
Hola @DaniRumpi.
Mi compañero @Saithan16 y yo hemos modificado las funciones del proyecto alastria-identity-lib y vamos a comenzar a modificar los ejemplos. Hay un comentario de @msalitu para coordinar esta tarea contigo. ¿Cómo lo hacemos?

**Comment by msalitu** [comment]
Hola @jotafernandez , primero hay que modificar los examples para comprobar que todo funciona antes de hacer los cambios en la demo con @DaniRumpi 

Lo que habría que hacer ahora es actualizar la nueva versión de la librería en el repositorio de example e ir modificando todas las llamadas a las funciones que habéis modificado para que reciban el DID y no el Alastria Proxy, @VictorNS69 puede indicaros si tenéis cualquier duda.

¡Muchas gracias a todos!

**Comment by DaniRumpi** [comment]
Hola, si, como dice @msalitu lo primero que hay que hacer es que en el example esté funcionando, y una vez quede todo probado ya me ocupo de adaptar vuestro cambio en la Demo.

Muchas gracias chicos, buen trabajo!

**Comment by jotafernandez** [comment]
Gracias!!! Pues así lo haremos.

**Comment by jotafernandez** [comment]
Buenos días, ya hemos modificado los examples con los cambios en las librerías. Pendiente de confirmación.

**Comment by nmanero** [comment]
I've uploaded changes in values in configuration.json and in variables in examples that were wrong according to tests:
In configuration.json

- dids without 0x and with incorrect characters, above [a-f]

- context property was a string and it should be an array

- levelOfAssurance should be an integer and it was a string

In examples:

- in the creation of tokens, the value of the property used as the networkId was the string "Alastria Network" instead of "redb" or "redt", so the tokens generated were not valid according to tests

**Comment by VictorNS69** [comment]
I'm not sure if the LOA level should be a number, string or can be both so it is an enum.
Maybe @msalitu can enlighten us.

**Comment by msalitu** [comment]
I suggest to use numbers to unify versions.

I have a question, should DID contain "0x" always ?

**Comment by VictorNS69** [comment]
In the W3C documentation (https://w3c.github.io/did-core/#a-simple-example) is not specified.
![image](https://user-images.githubusercontent.com/10101065/82203020-01100480-9903-11ea-9999-78ba4f8dfbe2.png)

So IMHO the DID should be without "0x", so there is no need to change all the examples and repositories. :laughing: 

Here is more info: https://w3c.github.io/did-core/#method-specific-parameters
![image](https://user-images.githubusercontent.com/10101065/82203805-16d1f980-9904-11ea-92f7-2838c6dd9c66.png)

**Comment by nmanero** [comment]
But then, it is not in hex format, because it admits other values than from a-f. Then actually, we should not admit any did with the 0x or, if we admit that, it seems that that won't represent an hex value, just the 0x characters. What do you think?

**Comment by DrankoLQ** [comment]
I agree. Just taking an overview of the link Victor has attached, it looks like is not a hex value so we shouldn't validate that the string has to start with `0x`, although it may be there without a problem.
