### ISSUE TITLE
COVID-1. Consultar validez clave pública example

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-example#46]
Generar un ejemplo de uso de la nueva función de la librería implementada en https://github.com/alastria/alastria-identity-lib/issues/47

**Comment by msalitu** [comment]
@VictorNS69 por favor, define con @nmanero el mejor lugar dentro del repositorio para emplazar este example. Se debería probar a añadir varias claves públicas a un DID y hacer distintas consultas.

**Comment by VictorNS69** [comment]
@nmanero .

Considero que deberíamos **reutilizar el directorio [examplePublicKey](https://github.com/alastria/alastria-identity-example/tree/develop/examplePublicKey)**.

Los ejemplos/scripts que se creen tienen que tener un **nombre identificador relevante**, como por ejemplo _1.getSubject1CurrentPublicKey.js_ que hace una consulta al _getCurrentPublicKey_ del _subject1_. Adicionalemnte, **al nombre se le pone un número, indicando el qué orden ha de ejecutarse**. Justo en este caso no es relevante ese numero, ya que da igual el orden en que ejecutes las consultas sobre la clave pública. Aún así, se le añadirá un número (el siguiente disponible) para tener la misma estructura que en el resto de ejemplos.

Estos scripts son **ejemplos de uso**, no test unitarios. Son ejemplos de cómo alguien que quiere usar la librería tiene que usarla para realizar cualquier historia de usuario. Por eso, **tienen que ser el "camino feliz"**.

Cualquier duda coméntame,

**Comment by nmanero** [comment]
Perfecto. Estuve "pegándome" para hacer funcionar un método que devolviera el status de una public key y siempre se me quejaba de que la key que enviaba no era un byte32 válido. ¿Si hago una prueba donde primero recupere la currentpublickey y ese valor lo envío al de validar el estado, debería funcionar o tengo que tener algo en cuenta que ahora se me escapa?

**Comment by VictorNS69** [comment]
> Perfecto. Estuve "pegándome" para hacer funcionar un método que devolviera el status de una public key y siempre se me quejaba de que la key que enviaba no era un byte32 válido. ¿Si hago una prueba donde primero recupere la currentpublickey y ese valor lo envío al de validar el estado, debería funcionar o tengo que tener algo en cuenta que ahora se me escapa?

Hola, en este ejemplo estamos haciendo la llamada a _getCurrentPublicKey_. Mira a ver si te ayuda en algo.

Por cierto, si estás trabajando en este issue, asignatelo :smile:

**Comment by nmanero** [comment]
Lo volveré a mirar pero entonces no me funcionó.

**Comment by VictorNS69** [comment]
> Lo volveré a mirar pero entonces no me funcionó.

Si quieres pasme traza del error por aquí o por privado.

**Es posible que los datos (did's) del fichero de configuración (configuration.json) estén obsoletos, y tengas que crear una nueva identidad jugando con los ejemplos**.

Prueba a lanzar este ejemplo: https://github.com/alastria/alastria-identity-example/blob/develop/exampleCreateAlastriaID/2.createEntity3AlastriaID.js
y luego este: https://github.com/alastria/alastria-identity-example/blob/develop/examplePublicKey/2.getEntity3CurrentPublicKey.js

En el ejemplo primero estás creando un DID para la "entidad3" y en el ejemplo 2 estás consultando su clave pública en la blockchain.

**Comment by nmanero** [comment]
Perfecto, lo miro y te digo algo.
Gracias!

**Comment by nmanero** [comment]
Comento las pruebas realizadas siempre con el mismo error: invalid bytes32 value (arg="publicKey"

Ejecuto los ejemplos que me comentaste, y con  https://github.com/alastria/alastria-identity-example/blob/develop/examplePublicKey/2.getEntity3CurrentPublicKey.js veu que se obtiene la publicKey. Si uso ese valor devuelto como parámetro del método getPublicKeyStatus de https://github.com/alastria/alastria-identity-lib/blob/develop/src/txFactory/publicKeyRegistryTransactionFactory.ts obtengo el error que comento.

Me da el mismo error si envío como parámetro, en lugar de la respuesta del método getCurrentPublicKey, el string fijo configData.entity3Pubk, empezando por 0x o sin empezar por el.
¿Cómo tendría que enviar este publicKey?

**Comment by VictorNS69** [comment]
> Comento las pruebas realizadas siempre con el mismo error: invalid bytes32 value (arg="publicKey"
> 
> Ejecuto los ejemplos que me comentaste, y con  https://github.com/alastria/alastria-identity-example/blob/develop/examplePublicKey/2.getEntity3CurrentPublicKey.js veu que se obtiene la publicKey. Si uso ese valor devuelto como parámetro del método getPublicKeyStatus de https://github.com/alastria/alastria-identity-lib/blob/develop/src/txFactory/publicKeyRegistryTransactionFactory.ts obtengo el error que comento.
> 
> Me da el mismo error si envío como parámetro, en lugar de la respuesta del método getCurrentPublicKey, el string fijo configData.entity3Pubk, empezando por 0x o sin empezar por el.
> ¿Cómo tendría que enviar este publicKey?

Hola! La clave pública tiene que ser escrita de la misma manera que se está almacenando en la blockchain. Creo que sin "0x".

Aún así, si te falla, habría que ver si por algún motivo, la función de la librería no está funcionando correctamente. Esto es posible, ya que no veo ninguna función que haga el test de esa función.

Por cierto, la función para obtener el estado de la clave pública recibe dos argumentos, la address y la clave pública. Prueba poniendo la address del keystore o con el proxy adddress que tenga dicho usuario.

Si sigues con problemas, te echo una mano investigando 👍

**Comment by nmanero** [comment]
Cuando uso el getCurrentPublicKey, un ejemplo de los datos que me devuelve en el data es 
0x31f7f25900000000000000000000000038e45abbc4cd44c21271173997a57791b3e3558d
Eso, sin contar el 0x, son 72 carácteres, si eso lo uso como parámetro publicKey del getPublicKeyStatus se queja que no son bytes32

Si de ese valor devuelto
0x31f7f25900000000000000000000000038e45abbc4cd44c21271173997a57791b3e3558d
me como los últimos carácteres hasta que tenga 32 bytes
0x31f7f25900000000000000000000000038e45abbc4cd44c21271173997a57791
Ya no falla el parámetro

¿pueden ir por ahí los tiros?

**Comment by VictorNS69** [comment]
@nmanero te comento:

He estado mirando los contratos, y he visto que, efectivamente esperamos byte32
![image](https://user-images.githubusercontent.com/10101065/80970221-18d38d00-8e1b-11ea-853e-0cf5f36463ab.png)
Pero en el resto de funciones, esperamos un string
![image](https://user-images.githubusercontent.com/10101065/80970260-2a1c9980-8e1b-11ea-86ba-e4a39fc1bed6.png)
Así que, lo que hay que hacer es pasar la clave pública en formato string (sin 0x) a byte32 usando el método `web3.utils.sha3()`.

Te adjunto el código que he hecho yo para probar
```js
const {transactionFactory} = require('alastria-identity-lib')
const Web3 = require('web3')
const fs = require('fs')

let rawdata = fs.readFileSync('../configuration.json')
let configData = JSON.parse(rawdata)

let myBlockchainServiceIp = configData.nodeURL
const web3 = new Web3(new Web3.providers.HttpProvider(myBlockchainServiceIp))

const did = "did:ala:quor:redT:8d6a04959dd35e97c599ad907817a1a12fd70f96"
const proxy_address = "8d6a04959dd35e97c599ad907817a1a12fd70f96" // address proxy
const address = "643266eb3105f4bf8b4f4fec50886e453f0da9ad" // address keystore
const pubKey = "aca7aa42e831f41b6f246d089fbcabe73e1c6ce01a1bb5d944fda4e148e1d6930f6ebb5138b1d103e3e384c893962a238e4088a549bfe84867da96942931f69a"
let getPubKstatusTx = transactionFactory.publicKeyRegistry.getPublicKeyStatus(web3, proxy_address, web3.utils.sha3(pubKey))

web3.eth.call(getPubKstatusTx)
.then(data => {
  let result = web3.eth.abi.decodeParameters(["bool","uint8", "uint256", "uint256"], data)
  let status = { 
    "exists": result[0],
    "status":result[1],
    "startDate": result[2],
    "endDate": result[3]
  }
  console.log("(Public Key Status) -----> ", status);
})
```
Y la solución tras la ejecución
![image](https://user-images.githubusercontent.com/10101065/80970604-b4fd9400-8e1b-11ea-9508-3b405f1997e9.png)

Espero que esto resuelva tus dudas :smiley:

**Comment by VictorNS69** [comment]
Por cierto, si mi código devuelve lo siguiente
![image](https://user-images.githubusercontent.com/10101065/80970761-f8f09900-8e1b-11ea-8942-1f55c2283910.png)
Es que los datos no están bien, y tendrás que crear una nueva identidad (did)

Cualquier cosa, coméntame

**Comment by nmanero** [comment]
Perfecto, ya lo he subido.
Los cambios afectan no solo a examples sino también al proyecto de librerías, con la rama #47 de aquel proyecto

**Comment by VictorNS69** [comment]
> Perfecto, ya lo he subido.
> Los cambios afectan no solo a examples sino también al proyecto de librerías, con la rama #47 de aquel proyecto

¿Entonces este issue ya está en una rama arreglado? Es que no veo la PR de este issue.

**Comment by nmanero** [comment]
Sí, había una rama asociada a las lib y otra esta. No he hecho el pull request, lo hago de ambas ramas?
