### ISSUE TITLE
Tests examples in the Besu Network

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-example#47]
Ejecutar todos los examples sobre un nodo de la Red-B cambiando de forma manual en la librería las address de los Smart Contracts de Alastria ID a los correspondientes desplegados por el equipo core de Besu en la redB

En caso de que funcione correctamente, se creará un nuevo issue para automatizar la configuración de estas address directamente en la librería.

**Comment by VictorNS69** [comment]
This task is now unlocked!

**Comment by alejandroalffer** [comment]
I've just deployed a regular node B on the AlastriaID server (EC2/AWS).

Once synchronized, I will deploy the SmartContracs, both the current version and the "pattern-proxy" ones.

```sh
root@ip-172-31-44-77:~# geth attach http://localhost:8545
Welcome to the Geth JavaScript console!
instance: besu/v20.10.2/linux-x86_64/oracle-java-16
coinbase: 0x32633cd8a67cac6363952bb9b3ae8d4282f884c4
at block: 174800 (Sat, 25 Jan 2020 11:58:42 UTC)
 modules: eth:1.0 net:1.0 web3:1.0
> eth.blockNumber
174800
> eth.syncing
false
```

**Comment by alejandroalffer** [comment]
First attemp works ok, but examples runs minning trasaccions in the node. But in Besu (and recent versions of GoQuorum) trasacctions should be minned in the client. So, we're working changing the task for using sendTrassacion, as seen in https://github.com/alejandroalffer/alastria-identity-example/commit/c7586e6f39c54eea1c5837472a2719e966854512

**Comment by alejandroalffer** [comment]
Besu address for AlastriaID Smart Contracts:
```
"Eidas":"0xb8bCaFdEb78Ae5Aa686c5D00616e1561Db0309d4",
"AlastriaServiceProvider":"0x83D65fAc900dB0A27B45854AC64DA3D25d97864d",
"AlastriaIdentityIssuer":"0xE8Dc811f7D05c44EfDD998FFfC26D610B0E5471e",
"AlastriaCredentialRegistry":"0x2f384716e73ae165bC3427Fd60550c26e6CB91c6",
"AlastriaPresentationRegistry":"0x95bC1119b764Bd678B68A1c03Cd8c06EfA27Df81",
"AlastriaPublicKeyRegistry":"0x19e33b2424c1D7B5E563E0A74d8b10CE3812469C",
"AlastriaIdentityManager":"0xE9B9a6E7700672DBbCe59664457D7E6F1dc00F3c",
"AlastriaNameService":"0xC1b1Fc2434D50966c28C8573AbdF3c7842a2Abb4"
```

This address should be used in config.ts from https://github.com/alastria/alastria-identity-lib/blob/develop/tsconfig.json

Also should be changed https://github.com/alastria/alastria-identity-example/blob/develop/configuration.json for use the RPC port for the node for example, http://alastria-id-ip:8454

The first example should be `createFirstEntity`, using https://github.com/alastria/alastriaID-truffle-contracts/blob/develop/accounts/serviceProvider-643266eb3105f4bf8b4f4fec50886e453f0da9ad. Then you should use `entity1` for creating the other roles... `entity2`... and the rest for the actors.

**Comment by alejandroalffer** [comment]
Examples **PASSED** for T and B networks using DigitelTS accounts and with  Issuer, Provider and Holder roles 👏👏👏👏

**Comment by mazh-lycan** [comment]
Examples PASSED for B network using alastria-identity-example's accounts EXCEPT FOR exampleEntities 1 to 7

**Comment by VictorNS69** [comment]
All examples in the besu network ([deploy-b-network](https://github.com/alastria/alastria-identity-example/tree/deploy-b-network) branch) have been successfully passed. Although a common bug has been detected in both networks with the example [examplePresentations/4.updateEntity2Presentation.js](https://github.com/alastria/alastria-identity-example/blob/deploy-b-network/examplePresentations/4.updateEntity2Presentation.js)

Related issue: https://github.com/alastria/alastriaID-truffle-contracts/issues/44

**Comment by VictorNS69** [comment]
Tested by me, and working both in T and B network.

Related info:
- https://github.com/alastria/alastriaID-truffle-contracts/pull/47
- https://github.com/alastria/alastria-identity-lib/pull/169
- https://github.com/alastria/alastria-identity-example/pull/130.

**Everything seems to be working fine** :rocket:
