### ISSUE TITLE
Release MVP1.5 examples

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-example#54]
Check that they are using the release version of the libs

**Comment by VictorNS69** [comment]
Several PR must be tested before creating the release

**Comment by VictorNS69** [comment]
What tasks have to be done before solving this issue?

**Comment by msalitu** [comment]
This MVP1 release should be done just after the Update Model issues are closed with the MVP1 version of the Smart Contracts

**Comment by VictorNS69** [comment]
Release after the lib release
