### ISSUE TITLE
Crear el ejemplo "5.deleteSubjectCredential"

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-example#71]
En el directorio de [exampleCredentials](https://github.com/alastria/alastria-identity-example/tree/develop/exampleCredentials) tiene que haber un example similar a [4.updateEntity1Credential.js](https://github.com/alastria/alastria-identity-example/blob/develop/exampleCredentials/4.updateEntity1Credential.js) pero que haga el ~`updateCredentialSubject`~ `deleteSubjectCredential`.

**Comment by amoral-eurogestion** [comment]
@VictorNS69, he revisado el otro ejemplo que sugerís pero no entiendo las cosas que hace.
Necesitaría saber que partes me sirven del ejemplo enlazado y que añadir para completar el ejemplo.
Me da la impresión que usa Ethereum y transacciones web, pero yo solo tengo conocimientos de back-end con Java.

**Comment by VictorNS69** [comment]
> @VictorNS69, he revisado el otro ejemplo que sugerís pero no entiendo las cosas que hace.
> Necesitaría saber que partes me sirven del ejemplo enlazado y que añadir para completar el ejemplo.
> Me da la impresión que usa Ethereum y transacciones web, pero yo solo tengo conocimientos de back-end con Java.

Tal vez lo más cómodo para los dos es que tengamos una call mañana y te lo explico detenidamente. 
Si quieres háblame por privado y acordamos una hora :smile:

**Comment by amoral-eurogestion** [comment]
Gracias @VictorNS69 , yo estoy disponible todo el día así que cualquier hora me viene bien.
También te comento que la partición no se cómo hacerla, no se en cuantos archivos o donde ponerlos.
En cuanto a la refactorización me pasa lo mismo que con esta tarea.

**Comment by VictorNS69** [comment]
@amoral-eurogestion tras hacer una revisión con los compañeros, hemos visto que **si se puede realizar esta tarea**.

**No** existe la función **`updateCredentialSubject`**, si no que **se llama `deleteSubjectCredential`**. La puedes encontrar aquí: https://github.com/alastria/alastria-identity-lib/blob/92b2f91918b9555b131077aae997565fa7493b32/src/txFactory/credentialRegistryTransactionFactory.ts#L46

Espero que con la información que te facilité el otro día, puedas realizar esta tarjeta sin ningún problema.

Aún así, si tienes dudas, pregúntame.
:smile:
